name: Simple Cross-Platform Build

on:
  push:
    tags:
      - 'v*'
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: latest
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DBUILD_GUI=ON -DGUI_USE_SDL2=ON -DGUI_STATIC_LINK=ON
    
    - name: Build
      run: cmake --build build --config ${{env.CMAKE_BUILD_TYPE}} --parallel
    
    - name: Package Artifacts
      run: |
        mkdir artifacts
        copy "build\Release\RTEgetData.exe" "artifacts\RTEgetData-CLI.exe" 2>nul || copy "build\RTEgetData.exe" "artifacts\RTEgetData-CLI.exe"
        copy "build\Release\RTEgetData-GUI.exe" "artifacts\RTEgetData-GUI.exe" 2>nul || copy "build\RTEgetData-GUI.exe" "artifacts\RTEgetData-GUI.exe"
        copy "Readme.md" "artifacts\"
        copy "LICENSE.md" "artifacts\"
        copy "CHANGELOG.md" "artifacts\"
        copy "BUILD.md" "artifacts\"
        
        echo @echo off > artifacts\run-cli.bat
        echo RTEgetData-CLI.exe %%* >> artifacts\run-cli.bat
        echo @echo off > artifacts\run-gui.bat  
        echo RTEgetData-GUI.exe %%* >> artifacts\run-gui.bat
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RTEgetData-Windows-x64-MSVC
        path: artifacts/
        retention-days: 90

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config libgl1-mesa-dev
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DBUILD_GUI=ON -DGUI_USE_SDL2=ON -DGUI_STATIC_LINK=ON
    
    - name: Build
      run: cmake --build build --parallel $(nproc)
    
    - name: Package Artifacts
      run: |
        mkdir artifacts
        cp build/RTEgetData artifacts/RTEgetData-CLI
        cp build/RTEgetData-GUI artifacts/RTEgetData-GUI
        cp Readme.md artifacts/
        cp LICENSE.md artifacts/
        cp CHANGELOG.md artifacts/
        cp BUILD.md artifacts/
        
        echo '#!/bin/bash' > artifacts/run-cli.sh
        echo './RTEgetData-CLI "$@"' >> artifacts/run-cli.sh
        echo '#!/bin/bash' > artifacts/run-gui.sh
        echo './RTEgetData-GUI "$@"' >> artifacts/run-gui.sh
        chmod +x artifacts/run-*.sh artifacts/RTEgetData-*
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RTEgetData-Linux-x64
        path: artifacts/
        retention-days: 90

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        brew install cmake pkg-config
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DBUILD_GUI=ON -DGUI_USE_SDL2=ON -DGUI_STATIC_LINK=ON
    
    - name: Build
      run: cmake --build build --parallel $(sysctl -n hw.ncpu)
    
    - name: Package Artifacts
      run: |
        mkdir artifacts
        cp build/RTEgetData artifacts/RTEgetData-CLI
        cp build/RTEgetData-GUI artifacts/RTEgetData-GUI
        cp Readme.md artifacts/
        cp LICENSE.md artifacts/
        cp CHANGELOG.md artifacts/
        cp BUILD.md artifacts/
        
        echo '#!/bin/bash' > artifacts/run-cli.sh
        echo './RTEgetData-CLI "$@"' >> artifacts/run-cli.sh
        echo '#!/bin/bash' > artifacts/run-gui.sh
        echo './RTEgetData-GUI "$@"' >> artifacts/run-gui.sh
        chmod +x artifacts/run-*.sh artifacts/RTEgetData-*
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RTEgetData-macOS-x64
        path: artifacts/
        retention-days: 90

  create-release:
    needs: [build-windows-msvc, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-artifacts/
    
    - name: Create Release Archives
      run: |
        cd all-artifacts
        
        # Create zip files for Windows
        for dir in RTEgetData-Windows-*; do
          if [ -d "$dir" ]; then
            zip -r "${dir}.zip" "$dir"
          fi
        done
        
        # Create tar.gz files for Linux and macOS
        for dir in RTEgetData-Linux-* RTEgetData-macOS-*; do
          if [ -d "$dir" ]; then
            tar -czf "${dir}.tar.gz" "$dir"
          fi
        done
        
        # Move archives to root
        mv *.zip *.tar.gz ../
        cd ..
        
        # Create checksums
        sha256sum *.zip *.tar.gz > checksums.sha256
        ls -la *.zip *.tar.gz checksums.sha256
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: RTEgetData ${{ steps.version.outputs.VERSION }}
        body: |
          # RTEgetData ${{ steps.version.outputs.VERSION }}
          
          Cross-platform data transfer utility for embedded systems.
          
          ## Downloads
          
          - **Windows**: `RTEgetData-Windows-x64-MSVC.zip`
          - **Linux**: `RTEgetData-Linux-x64.tar.gz`
          - **macOS**: `RTEgetData-macOS-x64.tar.gz`
          
          Each package contains both CLI and GUI versions with complete documentation.
          
          ## Verification
          
          Use `checksums.sha256` to verify file integrity:
          ```bash
          sha256sum -c checksums.sha256
          ```
        draft: false
        prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}
        files: |
          *.zip
          *.tar.gz
          checksums.sha256
        token: ${{ secrets.GITHUB_TOKEN }}

  build-summary:
    needs: [build-windows-msvc, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Build Summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Platform | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Windows MSVC | ${{ needs.build-windows-msvc.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Linux | ${{ needs.build-linux.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| macOS | ${{ needs.build-macos.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "🎉 **Release build completed!**" >> $GITHUB_STEP_SUMMARY
        else
          echo "📦 **Development build completed!**" >> $GITHUB_STEP_SUMMARY
        fi